/**
 * Utility functions for formatting content for PDF export
 */

/**
 * Format code for PDF display with syntax highlighting simulation
 *
 * @param {string} code The code to format
 * @param {string} language The programming language
 * @returns {string} HTML-formatted code ready for PDF
 */
export const formatCodeForPDF = (code) => {
  if (!code) return '';

  // Safely escape HTML and handle basic formatting
  return (
    code
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      // Preserve spaces and tabs
      .split('\n')
      .map((line) => {
        // Count leading spaces and convert to non-breaking spaces
        const leadingSpaces = line.match(/^\s*/)[0].length;
        const indent = '&nbsp;'.repeat(leadingSpaces);
        return `${indent}${line.trimStart()}`;
      })
      .join('<br>')
  );
};

/**
 * Create a styled PDF template for a notebook
 *
 * @param {Object} notebook The notebook object
 * @returns {string} HTML content ready for PDF conversion
 */
export const createNotebookPDFTemplate = (notebook) => {
  if (!notebook || !notebook.qa) return '';

  return `
    <div style="padding: 20px; font-family: Arial, sans-serif;">
      <h1 style="text-align: center; font-size: 24px; color: #000;">${notebook.name}</h1>
      <hr style="margin: 20px 0; border: none; border-top: 1px solid #000;" />
      ${notebook.qa
        .map(
          (qa, index) => `
        <div style="margin-bottom: 20px; break-inside: avoid;">
          <h3 style="margin: 0 0 10px 0; font-size: 16px;">Question ${index + 1}: ${qa.question}</h3>
          <p style="margin: 0 0 5px 0; font-size: 12px;">Language: ${qa.language}</p>
          <pre style="margin: 0; padding: 10px; background: #fff; border: 1px solid #ddd; border-radius: 4px;"><code style="font-family: 'Courier New', monospace; font-size: 12px; color: #000;">${formatCodeForPDF(qa.code)}</code></pre>
        </div>
        `
        )
        .join('')}
      <footer style="text-align: center; font-size: 10px; margin-top: 20px; color: #666;">
        Generated by LabBuddy on ${new Date().toLocaleDateString()}
      </footer>
    </div>
  `;
};
